sig-gis/triangulum

- .github/workflows/clojure.yml
- test/triangulum/core_test.clj
Testing Github workflow for automated testing
> Attempt at Github Actions

- deps.edn
- src/triangulum/build_db.clj
> Use cli tools for database

- README.org
- src/triangulum/https.clj
close #4 
close #5 
close #6 
close #12
> Update https for better clarity and resiliance

- .gitignore
- deps.edn
- src/triangulum/systemd.clj
> Add systemd library

- .github/PULL_REQUEST_TEMPLATE.md
Adds PR template to Triangulum.
> OPS-30 Add PR Template

- src/triangulum/utils.clj
Add new end-with util function
> Add 'end-with' function to utils

- src/triangulum/database.clj
- src/triangulum/deploy.clj
- src/triangulum/logging.clj
- src/triangulum/systemd.clj
> Add missing doc strings

- src/triangulum/https.clj
The cli namespace was added a while back.  Convert https to use the new methods.
> Convert https to use cli.clj

- src/triangulum/build_db.clj
Warn when SQL folders are missing instead of failing
> Add warnings for missing folders

- src/triangulum/config.clj
-------
Variadic arg handling is unnecessarily convoluted in get-config function.
Closes TRI-###
> Simplify triangulum.config/get-config

- deps.edn
- src/triangulum/utils.clj
- test/triangulum/utils_test.clj
Adds tests for all fns in `triangulum.utils`
Closes TRI-38
1. Run `clj -M:test`
> TRI-38 Add tests for triangulum.utils

- src/triangulum/type_conversion.clj
Adds generic pg->str method
Relates to CEO-211
> Add pg->str fn

- README.org
- src/triangulum/build_db.clj
- src/triangulum/cli.clj
Update cli.clj to merge config with cli params so we can rely on config.edn for consistent configuration. 
Closes TRI-55
> Update cli to take an optional map instead of required cli params and update build-db

- README.org
- src/triangulum/https.clj
> Update readme for https

- README.org
- src/triangulum/systemd.clj
- src/triangulum/utils.clj
Update systemd to use current cli code, and fix a couple things before deploying.
`clojure -A:systemd` to list the options.
> Update systemd to use current cli code

- src/triangulum/build_db.clj
- src/triangulum/sockets.clj
- src/triangulum/utils.clj
Add the `triangulum.sockets` namespace for shared use amongst projects.
Assists with TRI-69
> Add sockets namespace

- README.org
- config.example.edn
- src/triangulum/config.clj
- src/triangulum/https.clj
- src/triangulum/systemd.clj
- test/data/test_config.edn
- test/data/test_invalid_spec_config.edn
- test/data/test_missing_keys_config.edn
- test/data/test_new_config.edn
I couldnt get CEO to launch using the last version of spec and read in config.
> Clean up spec and CLI use of config.edn

- src/triangulum/build_db.clj
CEO has dev data to load, but only sometimes.  Add option to do so.
1. In CEO, run `build-db build-all --dev`
2. Check the DB to verify that this data loaded
> TRI-76 Add option to load dev data and refactor

- src/triangulum/config.clj
- src/triangulum/utils.clj
- test/triangulum/config_test.clj
- test/triangulum/utils_test.clj
Show missing keys and hard stop on error.  This should help diagnose the error and not miss it.  The server should 
Run test suit
> Show missing keys and hard stop on error

- README.org
> MISC-59 Update copyright

- src/triangulum/deploy.clj
-------
See PR title
Closes TRI-###
> Updated automatic library version assignments in triangulum.deploy/-main from yyyyMMDD to yyyy.MM.dd

- src/triangulum/systemd.clj
> Make parents for user systemd unit file

- src/triangulum/systemd.clj
> Use default target for user systemd service

- deps.edn
- src/triangulum/database.clj
> Add support for vector data type

- src/triangulum/utils.clj
This is the same as #96 but opened on this fork to make clj-kondo happy
> add sh-wrapper function to utils

- README.org
> Fix `set-log-path!` readme example

- src/triangulum/config.clj
> WIP: Added support for both nested and namespaced config.edn maps to triangulum.config

- src/triangulum/handler.clj
- src/triangulum/views.clj
The purpose of this merge request is to remove the `wrap-persistent-session` middleware function. The function merges keys from the `session` object onto `params` object; potentially overriding any existing values therein. 
This behavior made tackling a login/logout bug problematic on a client.  If there was an existing session object, and an
attempt was made to login, the submitted username was being overridden by the username in the session object. It was determined that merging params object values with session object values in this manner is not typical, so it was
removed.
In addition to removing the `wrap-persistent-session` function, separation of the `params` and `sessions` objects was
made explicit. Also, the values `:client-keys` and `:versionDeployed`, from `config.edn`, were …
> Remove `wrap-persistent-session` middleware

- src/triangulum/config.clj
- src/triangulum/utils.clj
Adds some spaces in logging messages and adds a few util functions.
> Fixing logging and adding some util functions

- src/triangulum/views.clj
A set of fixes to `views.clj` to better support Vite clients.
> Triangulum fixes to  better support dev-mode with Vite clients

- src/triangulum/utils.clj
A small syntactical update to the `current-year` function.
> Updating the current-year function

- config.namespaced-example.edn
- config.nested-example.edn
- deps.edn
- src/triangulum/config.clj
- src/triangulum/config_namespaced_spec.clj
- src/triangulum/config_nested_spec.clj
- src/triangulum/server.clj
- src/triangulum/worker.clj
> Refactor workers

- README.org
- src/triangulum/email.clj
- src/triangulum/errors.clj
- src/triangulum/utils.clj
- src/triangulum/views.clj
Enhance the existing documentation, incorporate provided feedback, and apply necessary revisions.
Closes TRIAN-93
> TRIAN-93 Feedback

- .github/workflows/clj-kondo.yml
- .github/workflows/clojure.yml
- .gitignore
- deps.edn
> [TRIAN-65] Update to latest clojure version (1.11 series) and other dependencies

- src/triangulum/handler.clj
Adds a routing handler that delegates authentication & redirection to handlers that are newly specified in a project's config.edn
> auth routing handler

- src/triangulum/packaging.clj
Small cleanup improvements to jar and uberjar builds
> No Ticket - Small cleanup updates to jar building functionality

- src/triangulum/handler.clj
> fixed var handling

- README.org
- config.namespaced-example.edn
- config.nested-example.edn
- src/triangulum/config_namespaced_spec.clj
- src/triangulum/config_nested_spec.clj
- src/triangulum/handler.clj
- test/data/test_config.edn
- test/data/test_new_config.edn
Added spec definitions for new config keys related to the authenticated routing handler. Updated default nested & namespaced config. Also created documentation for how to use this feature under readme -> handler.
> Dwhitaker/auth handler spec&config&docs

- config.namespaced-example.edn
- config.nested-example.edn
- src/triangulum/config.clj
- src/triangulum/config_namespaced_spec.clj
- src/triangulum/config_nested_spec.clj
- src/triangulum/handler.clj
- src/triangulum/server.clj
- src/triangulum/views.clj
- test/data/test_config.edn
This PR makes most of the keys optional.
Now, to get a webserver running, the only necessary keys are `:triangulum.server/http-port` and `:triangulum.server/handler`
> Relax spec

- src/triangulum/email.clj
> Improved logging and added a useful return value to triangulum.email/send-mail

- README.org
- test/data/test_new_config.edn
Remove deprecated `:session-key` key.
> Remove deprecated session-key key

- src/triangulum/worker.clj
> Added triangulum.worker/get-worker

- src/triangulum/handler.clj
- src/triangulum/logging.clj
> Her 648 revert

- src/triangulum/views.clj
Moves the flash message to the upper-right of the screen to follow normal UI conventions.
> Move the flash message to the right of the screen
