- .clj-kondo/config.edn
- .github/workflows/clj-kondo.yml
- .gitignore
Add Clojure linting for all pull-requests and branch pushes to catch errors early
1. Added `.clj-kondo/config.edn`
2. Add github workflow (`.github/workflows/clj-kondo.yml`) to check `src` and `test` directories
> Add CLJ-Kondo linter to Triangulum

- src/triangulum/https.clj
Allow user to initialize certbot for a domain without packaging cert for servers with multiple domains for the same server.
> Allow user to initialize certbot for a domain without packaging cert

- deps.edn
- src/triangulum/config.clj
- test/test_config.edn
- test/test_new_config.edn
- test/triangulum/config_test.clj
Enables reloading of the configuration file using `(config/load-config)`
Closes TRI-57
> TRI-57 Enable re/loading config file

- src/triangulum/config.clj
- src/triangulum/database.clj
- test/test_config.edn
- test/test_new_config.edn
Adds specs for `:database`, `:http`, and `:ssl` configurations. Checks that the entire `config.edn` file is valid before returning a config.
Closes TRI-56
> TRI-56 Add specs for config

- README.org
- src/triangulum/build_db.clj
Pass database variable to SQL
Closes TRI-60
1. When I use the -d database cli command, Then I am able to use the :database variable in my create_db.sql script.
> TRI-60 Pass database variable to SQL

- src/triangulum/database.clj
Adds a 2-arity form of `p-insert-rows!` so which defaults `fields` to `(keys (first rows))`.
Relates to CEO-211
> Add default p-insert-rows! fields arg

- README.org
- deps.edn
- src/triangulum/config.clj
Adds `clj -M:config validate [-f FILE]` command, which validates the file provided or the `config.edn` file by default.
Closes TRI-65
> TRI-65 Add config validate cli command

- src/triangulum/https.clj
Add webroot and email as optional inputs to https
`clojure -A:https certbot-init -d testing -e test@email.com -w /tmp`
> TRI-64 TRI-41 Add webroot and email as optional inputs to https

- src/triangulum/systemd.clj
The check for repo included the whole path string which can lead to false positives.
1. With a path /ceo/collect-earth-online, -r cannot be ceo
> Check folder and not full path for repo

- src/triangulum/systemd.clj
Modifies the systemd template to use the new `-M:server start/stop` commands.
> Update systemd template to use server start/stop

- src/triangulum/config.clj
- src/triangulum/utils.clj
- test/triangulum/utils_test.clj
Allow `config.edn` to have more keys and keys out of order compared to `config.default.edn`
Closes TRI-75
Run tests (`clj -M:test`)
> [TRI-75] Allow config.edn to use additional keys

- README.org
- deps.edn
- src/triangulum/notify.clj
- src/triangulum/systemd.clj
Modify systemd template use the `Type=notify` for services.
Added the `triangulum.notify` namespace, which wraps [SDNotify](https://github.com/faljse/SDNotify) library, which is a wrapper around [sd_notify](https://www.freedesktop.org/software/systemd/man/sd_notify.html).
New functions:
* `notify/available?`
* `notify/ready!`
* `notify/reloading!`
* `notify/stopping!`
* `notify/send-status!`
Updated the README to include new instructions for using `triangulum.notify`
Closes TRI-78
> TRI-78 Update systemd to use notify

- src/triangulum/cli.clj
- test/triangulum/cli_test.clj
Strips the :default parameter from the CLI options to be manually
merged later.
Prioritizes CLI values as follows:
1. CLI Flags
2. config.edn
3. Default values
Closes TRI-84
Run `clj -M:test`
> TRI-84 Fix default values overwrite config.edn

- src/triangulum/config.clj
- src/triangulum/systemd.clj
- test/triangulum/cli_test.clj
The `cli-options` must match the the generated keyword from the Clojure CLI parser (e.g. `"--dir DIR" -> :dir`)
Related to TRI-84
> Fix keywords to match CLI --option

- README.org
Adds documentation showing how to use the backup and restore build-db commands. CEO links to this README to explain how to get set up with a live copy of the DB.
> Document how to use the backup and restore build-db commands.

- README.org
- src/triangulum/systemd.clj
Switches the use of `systemd` to be run through the service user (e.g. `ceo`, `sig-app`). This allows us to avoid giving the service user `sudo` access, which would otherwise be needed in order to perform app restarts when updating the application.
Major changes:
* `systemctl` -> `systemctl --user`
* Removed `sudo` requirement
* Added README instructions on how to allow the user services to start on reboot.
Closes OPS-41
> Switch to user systemd services

- src/triangulum/utils.clj
Adding a new `sh-exec-with` function with the goal of returning a map containing the exit code, stdout, and stderr for only executing one command. Enhances the docstring for `sh-wrapper`
> Add a new sh-wrapper function

- deps.edn
BB is not compatible with clojure/data.json version `1.0.0`. Updated it to `2.4.0`
Importing triangulum.utils from a BB script should work without crashing and burning.
> Updating clojure/data.json version to work with BB

- .github/workflows/clojure.yml
- .gitignore
- README.org
- deps.edn
- src/triangulum/build_db.clj
- src/triangulum/migrate.clj
- src/triangulum/security.clj
- src/triangulum/systemd.clj
- src/triangulum/utils.clj
- test/triangulum/cli_test.clj
- test/triangulum/config_test.clj
- test/triangulum/core_test.clj
- test/triangulum/migrate_test.clj
- test/triangulum/security_test.clj
- test/triangulum/utils_test.clj
TRI-7 is meant to add a automatic database migration command to Triangulum
This is necessary to make auto-deployment possible for projects with databases, as well as help to simplify the challenges with tracking which DB migrations have been run.
From the `triangulu.migrate/migrate!` docs:
> Performs the database migrations stored in the `src/sql/changes/` directory.
> Migrations must be stored in chronological order (e.g. `2021-02-28_add-users-table.sql`).
>
>Migrations run inside of a transaction block to ensure the entire migration is completed prior to being committed to the database.
>
>  Currently, this tool does not support rollbacks.
>
>  If a migration fails, all migrations which follow it will be cancelled.
>
>  Migrations which have been completed are stored in a table …
> TRI-7 Add 'clj -M:build-db migrate' command

- config.namespaced-example.edn
- config.nested-example.edn
- src/triangulum/config_namespaced_spec.clj
- src/triangulum/config_nested_spec.clj
- src/triangulum/handler.clj
Specs to specify request and response keys to dissoc in the logging middleware.
Complements COL-481 
1. Define a set of request and response keys in the config file;
2. Run a server with triangulum;
3. When logging the request and response, the keys should not be included in the logs.
> COL-481: Add request keys to spec

- src/triangulum/config.clj
- src/triangulum/views.clj
Allow URLs to be used as static paths for js and css files. 
Closes TRIAN-98
1. In the config file for a project, try passing a URL for either `static-js-files` or `static-css-files`.
> TRIAN-98: Static files key can also contain urls

- config.namespaced-example.edn
- config.nested-example.edn
- src/triangulum/handler.clj
- src/triangulum/utils.clj
- src/triangulum/views.clj
Fixes the `:triangulum.views/cljs-init` key such that it works properly with CLJS webapps.
HER-113
> Fixes for CLJS webapps' cljs-init key

- src/triangulum/views.clj
Adds default styling to the flash message component (see screenshots below). The flash message pop up box will disappear after 10 seconds or when the user clicks the close button to mimic the functionality of the announcement banner.
HER-113
> Enhance the flash message functionality in views.clj

- deps.edn
- src/triangulum/systemd.clj
- src/triangulum/utils.clj
- Adds `triangulum.utils/path` to make it easier to generate path strings
- Adds `babashka.fs` as a library for Triangulum to feel more Clojure-y
- Replaces a few Java fns with the `fs/*` equivalent
- Uses babashka.fs to symlink `cljweb-<repo-name>.service` to
`multi-user.target.wants` dir
> Simplify systemd tool with `babashka.fs`

- deps.edn
- src/triangulum/systemd.clj
- src/triangulum/utils.clj
I was getting the following error:
```
sig-app@goshawk:~/forest-carbon-framework$ clojure -M:systemd enable -r "forest-carbon-framework"
03/29 21:05:43 cmd: systemctl --user daemon-reload
03/29 21:05:43 cmd: systemctl --user enable cljweb-forest-carbon-framework
03/29 21:05:43 error: Failed to enable unit: Unit file cljweb-forest-carbon-framework.service does not exist.
```
The issue was that even though `/opt/sig-app/.config/systemd/user/multi-user.target.wants/cljweb-forest-carbon-framework.service` existed, ` /opt/sig-app/.config/systemd/user/cljweb-forest-carbon-framework.service` did not. The fix is to copy the file to the `user` directory.
> Copy the systemd file into the user directory

- src/triangulum/systemd.clj
- src/triangulum/utils.clj
- test/triangulum/utils_test.clj
1. Using the new template with the `{{x}}` format causes parsing strings to erroneous getting replaced by `null` instead of `""` when "absent"
2. Java exception thrown while trying to parse java.nio.file.Path as a string in triangulum.utils/remove-end fn
1. Coerce nils to ""
2. transform the `Path` into a `String` before calling `remove-end`
> fixups after babashka migration and new parsing template

- src/triangulum/handler.clj
- src/triangulum/logging.clj
Added a longer character limit to logging to help with debugging requests that come through Triangulum. The logs would unhelpfully cut off before showing all of the details of input arguments, which made understanding the JSON request as it came through rather difficult.
Closes [HER-648](https://sig-gis.atlassian.net/browse/HER-648)
[HER-648]: https://sig-gis.atlassian.net/browse/HER-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Longer request logging

- README.org
- src/triangulum/config.clj
- src/triangulum/handler.clj
- src/triangulum/logging.clj
- src/triangulum/server.clj
Added a configurable flag to toggle the character limit in logging. This should help with debugging requests that come through Triangulum. The logs would unhelpfully cut off before showing all of the details of input arguments, which made understanding JSON requests as they came through rather difficult.
This flag keeps the default behavior of :truncate? for requests to be true, even if the key is missing from config.edn.
Closes [HER-648](https://sig-gis.atlassian.net/browse/HER-648)
[HER-648]: https://sig-gis.atlassian.net/browse/HER-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Truncate request config

- README.org
- config.namespaced-example.edn
- config.nested-example.edn
- src/triangulum/config.clj
- src/triangulum/config_namespaced_spec.clj
- src/triangulum/config_nested_spec.clj
- src/triangulum/handler.clj
- src/triangulum/server.clj
It's automatically being added without needing an explicit key to be set.
> Removing :truncate-request? from server config

- config.namespaced-example.edn
- config.nested-example.edn
- src/triangulum/config_namespaced_spec.clj
- src/triangulum/config_nested_spec.clj
- src/triangulum/handler.clj
Added configurable upload limits and progress tracking. Fixes 413 errors for large GSR policy file uploads. By default, handles files up to 100MB with progress updates.
TRI-112 GSR-69
Try uploading the sample portfolio CSV into GSR prod server
- Log in with an Admin account
- Click the Admin button on the upper right corner of the homepage
- Click the Select CSV File button under Upload CSV File
- Use the attached csv file: 
- Click Upload
> TRIAN-112 GSR-69  Extend maximum payload size to handle large csv data sets

- src/triangulum/views.clj
This allows any app using Triangulum, that servers up an app.js, to be included in a jar as long as it puts "target" on it's
deps.edn paths.
The change, as all jar supporting changes would be, is about changing it so a file that's accessed at runtime on the filepath, is instead a resource that is accessible on the  classpath (inside the jar).
In this case, that file is the manfiest.edn which is read at runtime on every Pyregence http request as part of triangulum.views/render-page. Here it is in https://github.com/pyregence/pyregence/blob/ca39bb36079dbcce6b6a34653650b36b0b7e8478/src/clj/pyregence/routing.clj#L13:
```
[:get "/"]                   {:handler (render-page "/")}
```
Here is the call tree that ends with render-page and starts with find-cljs-app-js:
```
▾   find-cljs-app-js …
```
> Add manifest.edn to classpath, so it can be accessed inside a jar.
